/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import business.DB4OUtil.DB4OUtil;
import business.Organization.Organization;
import business.EmployeeManagement;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saamu
 */
public class EmployeeStartUI extends javax.swing.JFrame {

    /**
     * Creates new form startUI
     */
    
    private EmployeeManagement system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public EmployeeStartUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("employee2.jpg")));
        system = dB4OUtil.retrieveSystem();
        this.setSize(1480, 1050);
        SignoutjButton.setVisible(false);
//        for(Organization organization:system.getOrganizationDirectory().getOrganizationList()){
//            System.out.println(organization.getName());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logincontainerJPanel = new javax.swing.JPanel();
        systemAdminLoginjPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sysadminUsernameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sysadminPasswordField = new javax.swing.JPasswordField();
        loginSysadminbtn = new javax.swing.JButton();
        SignoutjButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        logincontainerJPanel.setBackground(new java.awt.Color(237, 226, 242));

        systemAdminLoginjPanel.setBackground(new java.awt.Color(237, 226, 242));
        systemAdminLoginjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(153, 51, 255)), "Login Here", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 0, 255))); // NOI18N
        systemAdminLoginjPanel.setMinimumSize(new java.awt.Dimension(230, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Username");

        sysadminUsernameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        sysadminPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sysadminPasswordField.setMinimumSize(new java.awt.Dimension(8, 20));

        loginSysadminbtn.setBackground(new java.awt.Color(175, 180, 209));
        loginSysadminbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginSysadminbtn.setForeground(new java.awt.Color(0, 0, 102));
        loginSysadminbtn.setText("Login");
        loginSysadminbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginSysadminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSysadminbtnActionPerformed(evt);
            }
        });

        SignoutjButton.setBackground(new java.awt.Color(255, 102, 0));
        SignoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SignoutjButton.setText("Logout");
        SignoutjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SignoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoutjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout systemAdminLoginjPanelLayout = new javax.swing.GroupLayout(systemAdminLoginjPanel);
        systemAdminLoginjPanel.setLayout(systemAdminLoginjPanelLayout);
        systemAdminLoginjPanelLayout.setHorizontalGroup(
            systemAdminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminLoginjPanelLayout.createSequentialGroup()
                .addGroup(systemAdminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sysadminUsernameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sysadminPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginSysadminbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        systemAdminLoginjPanelLayout.setVerticalGroup(
            systemAdminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminLoginjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysadminUsernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysadminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginSysadminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout logincontainerJPanelLayout = new javax.swing.GroupLayout(logincontainerJPanel);
        logincontainerJPanel.setLayout(logincontainerJPanelLayout);
        logincontainerJPanelLayout.setHorizontalGroup(
            logincontainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logincontainerJPanelLayout.createSequentialGroup()
                .addComponent(systemAdminLoginjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logincontainerJPanelLayout.setVerticalGroup(
            logincontainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logincontainerJPanelLayout.createSequentialGroup()
                .addComponent(systemAdminLoginjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        container.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hi. Please Let System Admin authorize the System");
        jLabel1.setAutoscrolls(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/employee1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        container.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(logincontainerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logincontainerJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginSysadminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSysadminbtnActionPerformed
        // Get Admin user name
        String username = sysadminUsernameJTextField.getText();
        // Get Password
        char[] passwordstr = sysadminPasswordField.getPassword();
        String password = String.valueOf(passwordstr);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(username, password);
        Organization inOrganization=null;

        if(userAccount==null){
            //Step 2: Go inside each organization and check if the user is there
            for(Organization organization:system.getOrganizationDirectory().getOrganizationList()){
                userAccount=organization.getUserAccountDirectory().authenticateUser(username, password);
                if(userAccount!=null){
                    inOrganization=organization;
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Account Not Found or Wrong Password");
            return;
        }
        else{
            if(system.getUserAccountDirectory().IsSystemAdmin(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsEmployee(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsLearningAndDevelopmentHR(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsProjectManager(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsTalentAndAcquistionHR(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsCompensationAndBenefitsHR(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsAssetManager(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsTechSupport(userAccount.getRole().toString()) ||
                system.getUserAccountDirectory().IsFinanceManager(userAccount.getRole().toString())){
                CardLayout layout=(CardLayout)container.getLayout();
                container.add("workArea",userAccount.getRole().createWorkArea(logincontainerJPanel,container, userAccount, inOrganization, system));
                layout.next(container);
            }
            else{
                JOptionPane.showMessageDialog(null, "Dashboard not Ready for : "+userAccount.getRole().toString());
                return;
            }
        }
        sysadminUsernameJTextField.setText("");
        sysadminPasswordField.setText("");
        loginSysadminbtn.setVisible(false);
        SignoutjButton.setVisible(true);
        sysadminUsernameJTextField.setVisible(false);
        sysadminPasswordField.setVisible(false);
    }//GEN-LAST:event_loginSysadminbtnActionPerformed

    private void SignoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoutjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;

        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Signed Out.");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/employee1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);

        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        loginSysadminbtn.setVisible(true);
        SignoutjButton.setVisible(false);
        sysadminUsernameJTextField.setVisible(true);
        sysadminPasswordField.setVisible(true);
        container.add(jPanel6);
    }//GEN-LAST:event_SignoutjButtonActionPerformed
    
    public void closeLoginPanel(){
        this.logincontainerJPanel.setVisible(false);
        this.container.removeAll();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeStartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeStartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeStartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeStartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeStartUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignoutjButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton loginSysadminbtn;
    public javax.swing.JPanel logincontainerJPanel;
    private javax.swing.JPasswordField sysadminPasswordField;
    private javax.swing.JTextField sysadminUsernameJTextField;
    public javax.swing.JPanel systemAdminLoginjPanel;
    // End of variables declaration//GEN-END:variables
}
