/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LearningAndDevelopmentHR;

import business.DB4OUtil.DB4OUtil;
import business.Organization.OrganizationDirectory;
import business.EmployeeManagement;
import business.Organization.Organization;
import business.Trainees.Trainees;
import business.Trainings.Trainings;
import business.UserAccount.UserAccount;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class LearningDevelopmentHRWorkerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private EmployeeManagement system;
    private OrganizationDirectory directory;
    private Organization organization;
    private JPanel container,logincontainerJPanel;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private DefaultComboBoxModel days=new DefaultComboBoxModel();
    private DefaultComboBoxModel days1=new DefaultComboBoxModel();
    public LearningDevelopmentHRWorkerPanel(JPanel logincontainerJPanel,JPanel container,Organization organization, UserAccount user, EmployeeManagement system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.directory=directory;
        this.user=user;
        this.loggedmhwjLabel.setText("Welcome, "+user.getEmployee());
        approveTrainingjButton.setVisible(true);
        
        DisplayTrainings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        networknamejLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        approveTrainingjButton = new javax.swing.JButton();
        rejectTrainingjButton = new javax.swing.JButton();
        completeTrainingjButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        trainingsjTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        traineesjTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(237, 226, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        networknamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        networknamejLabel.setText("Learning And Development HR Dashboard");
        networknamejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Training Response", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        approveTrainingjButton.setBackground(new java.awt.Color(175, 180, 209));
        approveTrainingjButton.setText("Approve Training");
        approveTrainingjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        approveTrainingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveTrainingjButtonActionPerformed(evt);
            }
        });

        rejectTrainingjButton.setBackground(new java.awt.Color(175, 180, 209));
        rejectTrainingjButton.setText("Reject Training");
        rejectTrainingjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rejectTrainingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectTrainingjButtonActionPerformed(evt);
            }
        });

        completeTrainingjButton.setBackground(new java.awt.Color(175, 180, 209));
        completeTrainingjButton.setText("Complete Training");
        completeTrainingjButton.setToolTipText("");
        completeTrainingjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        completeTrainingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeTrainingjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completeTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(approveTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rejectTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(completeTrainingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane5.setBackground(new java.awt.Color(237, 226, 242));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trainings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        trainingsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project", "Manager", "Training", "Description", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainingsjTable.setGridColor(java.awt.SystemColor.window);
        trainingsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainingsjTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(trainingsjTable);

        jScrollPane1.setBackground(new java.awt.Color(237, 226, 242));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trainees", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        traineesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Training", "Project", "Trainee", "Assigned On", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        traineesjTable.setGridColor(java.awt.SystemColor.window);
        traineesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traineesjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(traineesjTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveTrainingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveTrainingjButtonActionPerformed
        int selectedRow = trainingsjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Training to Approve.");
            return;
        }
        
        Trainings training = (Trainings)trainingsjTable.getValueAt(selectedRow, 2);
        if(training==null) {
            JOptionPane.showMessageDialog(this, "Select Training First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        training.setStatus("Approved");
        JOptionPane.showMessageDialog(null, "Training Requested Approved");
        
        dB4OUtil.storeSystem(system);
        DisplayTrainings();
    }//GEN-LAST:event_approveTrainingjButtonActionPerformed

    private void trainingsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainingsjTableMouseClicked
        int selectedRow = trainingsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Training");
            return;
        }
        DisplayTrainees();
    }//GEN-LAST:event_trainingsjTableMouseClicked

    private void traineesjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traineesjTableMouseClicked
        int selectedRow = traineesjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Training Trainee");
            return;
        }
    }//GEN-LAST:event_traineesjTableMouseClicked

    private void rejectTrainingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectTrainingjButtonActionPerformed
        int selectedRow = trainingsjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Training to Reject.");
            return;
        }
        
        Trainings training = (Trainings)trainingsjTable.getValueAt(selectedRow, 2);
        if(training==null) {
            JOptionPane.showMessageDialog(this, "Select Training First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        training.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Training Requested Rejected");
        
        dB4OUtil.storeSystem(system);
        DisplayTrainings();
    }//GEN-LAST:event_rejectTrainingjButtonActionPerformed

    private void completeTrainingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeTrainingjButtonActionPerformed
        int selectedRow = trainingsjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Training to Complete.");
            return;
        }
        
        Trainings training = (Trainings)trainingsjTable.getValueAt(selectedRow, 2);
        if(training==null) {
            JOptionPane.showMessageDialog(this, "Select Training First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        training.setStatus("Completed");
        JOptionPane.showMessageDialog(null, "Training is Completed");
        
        dB4OUtil.storeSystem(system);
        DisplayTrainings();
    }//GEN-LAST:event_completeTrainingjButtonActionPerformed

    private void DisplayTrainees() {
        int selectedRow = trainingsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Training");
            return;
        }
        
        Trainings training = (Trainings)trainingsjTable.getValueAt(selectedRow, 2);
        DefaultTableModel model = (DefaultTableModel) traineesjTable.getModel();
        
        model.setRowCount(0);
        for (Trainees trainess : system.getTraineesDirectory().getTraineesList()) {
            if(trainess.getTraining().equals(training)){
                Object[] row = new Object[5];
                row[0] = trainess.getTraining();
                row[1] = trainess.getProject();
                row[2] = trainess;
                row[3] = trainess.getAssignedOn();
                row[4] = trainess.getStatus();
                model.addRow(row);
            }
        }
    }
    
    private void DisplayTrainings(){
        DefaultTableModel model = (DefaultTableModel) trainingsjTable.getModel();
        
        model.setRowCount(0);
        for (Trainings training : system.getTrainingsDirectory().getTrainingsList()) {
            Object[] row = new Object[5];
            row[0] = training.getProject();
            row[1] = training.getProjectManager();
            row[2] = training;
            row[3] = training.getDescription();
            row[4] = training.getStatus();
            model.addRow(row);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveTrainingjButton;
    private javax.swing.JButton completeTrainingjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JLabel networknamejLabel;
    private javax.swing.JButton rejectTrainingjButton;
    private javax.swing.JTable traineesjTable;
    private javax.swing.JTable trainingsjTable;
    // End of variables declaration//GEN-END:variables
}
