/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdmin;

import business.EmployeeManagement;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class SystemAdminWorkerjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private EmployeeManagement system;
    private JPanel container,logincontainerJPanel;
    private UserAccount user;
    public SystemAdminWorkerjPanel(JPanel logincontainerJPanel,JPanel container, UserAccount user, EmployeeManagement system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.user=user;
        this.SignedInUserjLabel.setText("Welcome, "+user.getEmployee());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        manageHRjButton = new javax.swing.JButton();
        manageITSupportjButton = new javax.swing.JButton();
        mangeProjectsjButton = new javax.swing.JButton();
        mangeFinancejButton = new javax.swing.JButton();
        SignedinRolejLabel = new javax.swing.JLabel();
        SignedInUserjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 226, 242));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        manageHRjButton.setBackground(new java.awt.Color(175, 180, 209));
        manageHRjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageHRjButton.setText("Manage HR");
        manageHRjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 153, 153)));
        manageHRjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHRjButtonActionPerformed(evt);
            }
        });

        manageITSupportjButton.setBackground(new java.awt.Color(175, 180, 209));
        manageITSupportjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageITSupportjButton.setText("Manage IT Support");
        manageITSupportjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 153, 153)));
        manageITSupportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageITSupportjButtonActionPerformed(evt);
            }
        });

        mangeProjectsjButton.setBackground(new java.awt.Color(175, 180, 209));
        mangeProjectsjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mangeProjectsjButton.setText("Manage Projects");
        mangeProjectsjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 153, 153)));
        mangeProjectsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeProjectsjButtonActionPerformed(evt);
            }
        });

        mangeFinancejButton.setBackground(new java.awt.Color(175, 180, 209));
        mangeFinancejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mangeFinancejButton.setText("Manage Finance");
        mangeFinancejButton.setToolTipText("");
        mangeFinancejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 153, 153)));
        mangeFinancejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeFinancejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mangeProjectsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageITSupportjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(manageHRjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mangeFinancejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageHRjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageITSupportjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mangeProjectsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mangeFinancejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        SignedinRolejLabel.setBackground(new java.awt.Color(255, 255, 255));
        SignedinRolejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SignedinRolejLabel.setText("System Admin Dashboard");
        SignedinRolejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SignedInUserjLabel.setBackground(new java.awt.Color(255, 255, 255));
        SignedInUserjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SignedInUserjLabel.setText("Logged Username");
        SignedInUserjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(SignedinRolejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignedInUserjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignedinRolejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignedInUserjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageHRjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHRjButtonActionPerformed
        SystemAdminWorkerHRPanel systemAdminWorkerHRPanel=new SystemAdminWorkerHRPanel(logincontainerJPanel,container,system.getOrganizationDirectory(), user ,system);
        container.add("systemAdminWorkerHRPanel",systemAdminWorkerHRPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);   
    }//GEN-LAST:event_manageHRjButtonActionPerformed

    private void manageITSupportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageITSupportjButtonActionPerformed
        SystemAdminWorkerITSupportPanel systemAdminWorkerITSupportPanel=new SystemAdminWorkerITSupportPanel(logincontainerJPanel,container,system.getOrganizationDirectory(), user ,system);
        container.add("systemAdminWorkerITSupportPanel",systemAdminWorkerITSupportPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);   
    }//GEN-LAST:event_manageITSupportjButtonActionPerformed

    private void mangeProjectsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeProjectsjButtonActionPerformed
        SystemAdminWorkerProjectPanel systemAdminWorkerProjectPanel=new SystemAdminWorkerProjectPanel(logincontainerJPanel,container,system.getOrganizationDirectory(), user ,system);
        container.add("systemAdminWorkerProjectPanel",systemAdminWorkerProjectPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);   
    }//GEN-LAST:event_mangeProjectsjButtonActionPerformed

    private void mangeFinancejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeFinancejButtonActionPerformed
        SystemAdminWorkerFinancePanel systemAdminWorkerFinancePanel=new SystemAdminWorkerFinancePanel(logincontainerJPanel,container,system.getOrganizationDirectory(), user ,system);
        container.add("systemAdminWorkerFinancePanel",systemAdminWorkerFinancePanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container); 
    }//GEN-LAST:event_mangeFinancejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignedInUserjLabel;
    private javax.swing.JLabel SignedinRolejLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton manageHRjButton;
    private javax.swing.JButton manageITSupportjButton;
    private javax.swing.JButton mangeFinancejButton;
    private javax.swing.JButton mangeProjectsjButton;
    // End of variables declaration//GEN-END:variables
}
